# Generated by Django 6.1.1 on 2026-10-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_title_task_unique_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_title',
        ),
    ]
